# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ef9e9d8dc54ea6b808177f3224bc7bdbccb1d80235df4b9c8611df70c388a793df07511b4cd288c538acc335d90ba14e9a10a6e892eb31ac7bcb928b374ef79

test:
  secret_key_base: 54f19ddda232d68282dd68a782107246cdde96b80ff5d11f2709320b7e5339ef500d0e2c17fb6e9ac43b5b70f5b1f584bae9088d5d0080f5effd5ac9b04434a4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
